package com.ssm.blog.mapper;

import com.ssm.blog.view.TypeInfo;
import com.ssm.blog.view.TypeInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TypeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated Wed Apr 04 16:00:39 CST 2018
     */
    int countByExample(TypeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated Wed Apr 04 16:00:39 CST 2018
     */
    int deleteByExample(TypeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated Wed Apr 04 16:00:39 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated Wed Apr 04 16:00:39 CST 2018
     */
    int insert(TypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated Wed Apr 04 16:00:39 CST 2018
     */
    int insertSelective(TypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated Wed Apr 04 16:00:39 CST 2018
     */
    List<TypeInfo> selectByExample(TypeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated Wed Apr 04 16:00:39 CST 2018
     */
    TypeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated Wed Apr 04 16:00:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") TypeInfo record, @Param("example") TypeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated Wed Apr 04 16:00:39 CST 2018
     */
    int updateByExample(@Param("record") TypeInfo record, @Param("example") TypeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated Wed Apr 04 16:00:39 CST 2018
     */
    int updateByPrimaryKeySelective(TypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated Wed Apr 04 16:00:39 CST 2018
     */
    int updateByPrimaryKey(TypeInfo record);
}