package com.ssm.blog.view;

import java.util.Date;

public class ArticleInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.id
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.user_id
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.type_id
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.view_count
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    private Integer viewCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.title
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.content_text
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    private String contentText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.cover
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    private String cover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.update_time
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.status
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.content
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.id
     *
     * @return the value of article_info.id
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    
    private String type_name;
    

	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.id
     *
     * @param id the value for article_info.id
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.user_id
     *
     * @return the value of article_info.user_id
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.user_id
     *
     * @param userId the value for article_info.user_id
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.type_id
     *
     * @return the value of article_info.type_id
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.type_id
     *
     * @param typeId the value for article_info.type_id
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.view_count
     *
     * @return the value of article_info.view_count
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.view_count
     *
     * @param viewCount the value for article_info.view_count
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.title
     *
     * @return the value of article_info.title
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.title
     *
     * @param title the value for article_info.title
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.content_text
     *
     * @return the value of article_info.content_text
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public String getContentText() {
        return contentText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.content_text
     *
     * @param contentText the value for article_info.content_text
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public void setContentText(String contentText) {
        this.contentText = contentText == null ? null : contentText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.cover
     *
     * @return the value of article_info.cover
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.cover
     *
     * @param cover the value for article_info.cover
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.update_time
     *
     * @return the value of article_info.update_time
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.update_time
     *
     * @param updateTime the value for article_info.update_time
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.status
     *
     * @return the value of article_info.status
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.status
     *
     * @param status the value for article_info.status
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.content
     *
     * @return the value of article_info.content
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.content
     *
     * @param content the value for article_info.content
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
    
    public String getType_name() {
		return type_name;
	}

	public void setType_name(String type_name) {
		this.type_name = type_name;
	}
}