package com.ssm.blog.view;

public class TypeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type_info.id
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type_info.user_id
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type_info.name
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type_info.sort_no
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    private Integer sortNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type_info.id
     *
     * @return the value of type_info.id
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type_info.id
     *
     * @param id the value for type_info.id
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type_info.user_id
     *
     * @return the value of type_info.user_id
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type_info.user_id
     *
     * @param userId the value for type_info.user_id
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type_info.name
     *
     * @return the value of type_info.name
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type_info.name
     *
     * @param name the value for type_info.name
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type_info.sort_no
     *
     * @return the value of type_info.sort_no
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public Integer getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type_info.sort_no
     *
     * @param sortNo the value for type_info.sort_no
     *
     * @mbggenerated Wed Apr 04 16:12:14 CST 2018
     */
    public void setSortNo(Integer sortNo) {
        this.sortNo = sortNo;
    }
}